### PR TITLE
Add -Wno-unused-function to supress-warnings.cmake

### PR DESCRIPTION
**Pull request by andresag01**
@rgrover  @LiyouZhou

### CODE REVIEW

**Comment by LiyouZhou** [comment]
@andresag01 These warnings come from nordic files or our files? If it is our files, can't we fix the sourcefile? if it is nordic, does it work if we put this cmake file in nrf51-module?

**Comment by andresag01** [comment]
The come from the nordic files, but they are included by our files. We already introduced some additional fixes for the nordic files as well. Have a look at [this PR](https://github.com/ARMmbed/nrf51-sdk/pull/7)

**Comment by rgrover** [comment]
This looks good to me. 

To answer LiYou: In many cases, the problems originate from headers in the nordic SDK, but then manifest when these headers are included in sources from ble-nrf51822 (or elsewhere).

**Comment by rgrover** [comment]
@LiyouZhou bump

**Comment by rgrover** [comment]
oh no, this was merged into 'master'
:(
it should have gone into 'develop'

**Comment by rgrover** [comment]
I've deleted this merge from the history

**Comment by rgrover** [comment]
merged into develop. 
published ble-nrf51822-2.2.2

**Pull request merged**
