### PR TITLE
Sync develop against master

### PR DESCRIPTION
**Pull request by pan-**
Some commits from master are not included in develop,
This PR intends to fix this.

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by pan-** [comment]
retest this please.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by pan-** [comment]
retest this please

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by pan-** [comment]
retest this please.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by pan-** [comment]
retest this please.

**Pull request merged**
