### PR TITLE
fix backward compatibility with s110

### PR DESCRIPTION
**Pull request by zskdan**
ble-nrf51822 is no more compatible with s110. 

Signed-off-by: Zakaria ELQotbi <zakaria@elqotbi.com>

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by pan-** [comment]
I close this PR, it is a duplicate of https://github.com/ARMmbed/ble-nrf51822/pull/109.

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Pull request closed without merging**
